config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }

  authenticated :user do
    root to: 'patients#index', as: :authenticated_root
  end

  # ログインしていないユーザーのデフォルトのルート
  unauthenticated do
    root to: 'deshboard#index', as: :unauthenticated_root
  end

  
  resources :patients, only: [:index, :new, :create, :show, :edit] do
    resources :medications, only: [:new, :create]
  end
  
end

app/models/medication.rb
class Medication < ApplicationRecord
  belongs_to :patient
  has_many :prescriptions
end

app/controllers/medications_controller.rb
class MedicationsController < ApplicationController
  before_action :set_patient

  def new
    @medication_prescription_form = MedicationPrescriptionForm.new
  end

  def create
    @medication_prescription_form = MedicationPrescriptionForm.new(medication_prescription_params)
    
    if @medication_prescription_form.save
      redirect_to patient_path(@patient)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private
  def set_patient
    @patient = Patient.find(params[:patient_id])
  end

  def patient
    @patient
  end

  def medication_prescription_params
    params.require(:medication_prescription_form).permit(
      :medicine_name, :description, :dosage, :side_effect, 
      :frequency, :duration,
      :doctor_name, :clinic_name, :phone_number,
      :pharmacist, :pharmacy_name, :phone_number
    ).merge(patient_id: patient.id)
  end
end

app/helpers/medications_helper.rb
module MedicationsHelper
end

app/views/medications/new.html.erb
<div class='bg-body-secondary p-3'>
  <div class='bg-body container py-3'>

    <%= form_with model: @medication_prescription_form, url: patient_medications_path do |f| %>
    <%= render 'shared/error_messages', model: f.object %>

      <div class='p-3'>
        <%= f.label :medicine_name, 'お薬名', class: 'form-label'  %>
        <%= f.text_field :medicine_name, class:"form-control" %>
      </div>

      <div class='p-3'>
        <%= f.label :description, '説明', class: 'form-label' %>
        <%= f.text_area :description, class:"form-control" %>
      </div>

      <div class='p-3'>
        <%= f.label :dosage, '一回あたりの量', class: 'form-label' %>
        <%= f.text_field :dosage, class:"form-control" %>
      </div>

      <div class='p-3'>
        <%= f.label :side_effect, '副作用', class: 'form-label' %>
        <%= f.text_area :side_effect, class:"form-control" %>
      </div>

      <div class='p-3'>
        <%= f.label :frequency, '飲むタイミング', class: 'form-label' %>
        <%= f.text_field :frequency, class:"form-control" %>
      </div>

      <div class='p-3'>
        <%= f.label :duration, '処方期間', class: 'form-label' %>
        <%= f.text_field :duration, class:"form-control" %>
      </div>

      <div class='p-3'>
        <%= f.label :doctor_name, '医者名', class: 'form-label' %>
        <%= f.text_field :doctor_name, class:"form-control" %>
      </div>

      <div class='p-3'>
        <%= f.label :clinic_name, '病院名', class: 'form-label' %>
        <%= f.text_field :clinic_name, class:"form-control" %>
      </div>

      <div class='p-3'>
        <%= f.label :phone_number, '電話番号', class: 'form-label' %>
        <%= f.text_field :phone_number, class:"form-control" %>
      </div>

      <div class='p-3'>
        <%= f.label :pharmacist, '薬剤師名', class: 'form-label' %>
        <%= f.text_field :pharmacist, class:"form-control" %>
      </div>

      <div class='p-3'>
        <%= f.label :pharmacy_name, '薬局名', class: 'form-label' %>
        <%= f.text_field :pharmacy_name, class:"form-control" %>
      </div>

      <div class='p-3'>
        <%= f.label :phone_number, '電話番号', class: 'form-label' %>
        <%= f.text_field :phone_number, class:"form-control" %>
      </div>

      <div class='p-3 d-grid gap-2 col-6 mx-auto'>
        <%= f.submit "記録する" %>
      </div>
    <% end %>
  </div>
</div>