config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }

  authenticated :user do
    root to: 'patients#index', as: :authenticated_root
  end

  # ログインしていないユーザーのデフォルトのルート
  unauthenticated do
    root to: 'deshboard#index', as: :unauthenticated_root
  end

  
  resources :patients, only: [:index, :new, :create, :show, :edit] do
    resources :medications, only: [:new, :create]
  end
  
end

app/models/patient.rb
class Patient < ApplicationRecord
  belongs_to :user
  has_many :medications
  has_many :prescriptions
  has_many :doctors
  has_many :pharmacies

  # has_many :appointments

  validates :patient_name, presence: true
  validates :birthdate, presence: true
  validates :user_id, presence: true
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :authenticate_user!, only: [:index, :new, :create] 

  def index
    @patients = Patient.all
  end

  def new
    @patient = Patient.new
  end

  def create
    @patient = Patient.new(patient_params)

    if @patient.save
      redirect_to authenticated_root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @patient = Patient.find(params[:id])
    @medication_prescription_data = MedicationPrescriptionForm.find_by_patient(@patient.id)
  end

  def edit
    @patient = Patient.find(params[:id])
  end
  
  private

  def patient_params
    params.require(:patient).permit(:patient_name, :birthdate, :gender).merge(user_id: current_user.id)
  end

end

app/helpers/patient_helper.rb
module PatientHelper
end

app/views/patients/index.html.erb
<div class='bg-body-secondary p-3'>

  <div class='patient_head'>
    <h4>ようこそ、<%= current_user.nickname %>さん</h4>
  </div>

  <div class='bg-body container py-3'>
    <div class='text-center'>
      <h3 class='text-center'>利用者を選択してください</h3>
      <%= link_to '新規利用者登録',  new_patient_path, class: 'link-dark link-offset-2 link-underline-opacity-0 link-underline-opacity-100-hover' %>
      <% @patients.each do |patient| %>
        <div class="patient">
          <%= link_to patient.patient_name, patient_path(patient.id), class: 'link-dark link-offset-2 link-underline-opacity-0 link-underline-opacity-100-hover'%>
        </div>
      <% end %>
    </div>
    <div class='text-center'>
      <div class='patient'>
      <%= link_to '診察予約',   class: "link-dark link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover" %>  ※現在調整中です
      </div>
    </div>
  </div>
</div>

app/views/patients/new.html.erb
<div class='bg-body-secondary p-3'>
  
  <%= form_with model: @patient, local: true do |f| %>

  <div class='bg-body container py-3'>
    <div class="field p-3">
      <%= f.label :patient_name, "名前" %>
      <%= f.text_field :patient_name, class: "form-control" %>
    </div>

    <div class="field p-3">
      <%= f.label :birthdate, "誕生日" %>
      <%= f.date_field :birthdate, class: "form-control" %>
    </div>

    <div class="field p-3">
      <%= f.label :gender, "性別" %>
      <%= f.select :gender, ["男", "女"], class: "form-control" %>
    </div>

    <button type="submit" class="btn btn-primary">登録</button>
  <% end %>
  </div>
</div>

app/views/patients/show.html.erb
<div class='bg-body-secondary p-3'>
  <div class='bg-body container py-3'>
    <div class="patient-info">
      <p>名前: <%= @patient.patient_name %></p>
      <p>誕生日: <%= @patient.birthdate %></p>
      <p>性別: <%= @patient.gender %></p>
    </div>
  </div>
  <div class='bg-body container '>
    <div class="today-prescriptions">
      <h2>今日の処方</h2>
      
      
      <% @medication_prescription_data[:medications].each do |medication| %>
      <p>
        <strong>薬名:</strong> <%= medication.medicine_name %><br>
        <strong>説明:</strong> <%= medication.description %><br>
        <strong>用量:</strong> <%= medication.dosage %><br>
        <strong>副作用:</strong> <%= medication.side_effect %>
      </p>
      
    <% end %>
    <h2>処方の情報</h2> 
    <% @medication_prescription_data[:prescriptions].each do |prescription| %> 
      <p>
        <strong>頻度:</strong> <%= prescription.frequency %><br>
        <strong>期間:</strong> <%= prescription.duration %>
      </p>
    <% end %>

    <h2>医者の情報</h2>
    <% @medication_prescription_data[:doctors].each do |doctor| %>
      <p>
        <strong>医者の名前:</strong> <%= doctor.doctor_name %><br>
        <strong>クリニックの名前:</strong> <%= doctor.clinic_name %><br>
        <strong>電話番号:</strong> <%= doctor.phone_number %>
      </p>
    <% end %>

    <h2>薬局の情報</h2>
    <% @medication_prescription_data[:pharmacies].each do |pharmacy| %>
      <p>
        <strong>薬剤師:</strong> <%= pharmacy.pharmacist %><br>
        <strong>薬局名:</strong> <%= pharmacy.pharmacy_name %><br>
        <strong>電話番号:</strong> <%= pharmacy.phone_number %>
      </p>
    <% end %>
    </div> 

    <%= link_to 'お薬登録', new_patient_medication_path(@patient.id) %>

    <div class="next-appointment">
      <h2>次の診察予約</h2>
      
        <p>次の予約はありません。</p>
    </div>
  </div>
</div>